### ISSUE TITLE
Model is not loaded when cpu is used

### ISSUE THREAD

**Issue by smttsp** [hackingmaterials/pv-vision#11]
https://github.com/hackingmaterials/pv-vision/blob/5ffdd6f02ab045cbfcd48390094ff9b50f906c45/pv_vision/nn/modelhandler.py#L344

This code fails when the device is `cpu`. It should be updated as below

```
        self.model.load_state_dict(
            torch.load(path, map_location=torch.device(self.device))
        )
```

**Comment by X-Chen97** [comment]
Hello! Thank you for pointing this out. If you are loading my model weights that were pretrained on GPU on a CPU device, your correction is necessary. I will update the codes.

**Comment by smttsp** [comment]
@X-Chen97 

cool. thank you!

**Comment by yahyaozturk** [comment]
@smttsp thank you for the fix, I faced the same problem and the model works now.

**Comment by X-Chen97** [comment]
fixed
