### ISSUE TITLE
How to obtain masks from raw images

### ISSUE THREAD

**Issue by smttsp** [hackingmaterials/pv-vision#13]
Hi there,

I was playing with the repo and I like the cleanliness and the quality of the code. Great job on that!

One issue I faced was that I couldn't figure out which model you were using to extract masks from raw images. I looked at all the notebooks but it is not clear to me at this point. I bet that it is [module segmentation](https://datahub.duramat.org/dataset/neural-network-weights/resource/4bfb4a89-277d-4e48-abfe-96d7d1800b51) but I am not 100% sure. 

I found `pipeline.sh` but it seems that it is mostly legacy work.

Could you please share a reference code if you have any available to perform that operation?

Thank you!

**Comment by X-Chen97** [comment]
Hello!

Please confirm whether you want to extract masks of cracks, busbars etc. from the single cell images, or masks of a whole module from the tilted images.

This [module segmentation](https://datahub.duramat.org/dataset/neural-network-weights/resource/4bfb4a89-277d-4e48-abfe-96d7d1800b51) allows to to extract module masks. But please note that our modules may not be the same as yours, so you will need to retrain that model using modelhandler in pv-vision. You can refer to this [paper](https://www.sciencedirect.com/science/article/pii/S0038092X22004571) for the module segmentation

And for the crack segmentation, you can find the model weights [here](https://datahub.duramat.org/dataset/neural-network-weights/resource/45da3b55-fa96-471d-a231-07b98ec5dd8e). You can refer to this [paper](https://ieeexplore.ieee.org/abstract/document/10066156) for more information.

Thanks!

**Comment by X-Chen97** [comment]
I will close this issue since there are no further questions asked. Feel free to raise new issues if you need help.
