### ISSUE TITLE
module cellsize issue

### ISSUE THREAD

**Issue by wt163** [hackingmaterials/pv-vision#15]
cause the type of module is square in example image, so the cellsize can be set into 250. but if rectangle module, can the cellsize be set different size by using array, list ect?

**Comment by wt163** [comment]
the cellsize setting error: TypeError: Invalid shape (60, 250, 250) for image data.
However, it doesn't effect the image segmentation.

**Comment by X-Chen97** [comment]
Hello! Could you please specify which codes or tutorials you are referring to? Also, I would assume you are talking about the segmentation of a rectangle cell (half-cut) rather than a rectangle module? Technically the algorithms should be able to segment the cells with any shapes. Thanks!

**Comment by cci-cgunaydin** [comment]
**transform_contour_rounded.ipynb** 
When I ran this tutorial for half-cut pv module image (below)

![SPE-09-2306130607](https://github.com/hackingmaterials/pv-vision/assets/80832978/a6250792-c068-431d-8bc3-8698d91f8545)

the below code does not help me specify cell size (300X150), if I use 300 as cellsize value, the image is still not processed correctly

```
img_transformed = raw_module.transform(cellsize=300, img_only=True)
plt.imshow(img_transformed, 'gray')
```

![output](https://github.com/hackingmaterials/pv-vision/assets/80832978/248dbb83-dd65-40ae-901a-fd6701c4294c)


Can you give us more detail on what to do with half-cut images?

**Comment by X-Chen97** [comment]
Our code was not tested on half-cut cells yet. I will look into this image and give you feedback soon

**Comment by X-Chen97** [comment]
Fixed. Now you can pass a tuple to the cellsize to indicate the (width, height) of your half cut cell
