### ISSUE TITLE
Add DOI and URL to citation

### ISSUE THREAD

**Issue by williamhobbs** [hackingmaterials/pv-vision#7]
It would be helpful to add a DOI, and possibly URL, to the readme here: https://github.com/hackingmaterials/pv-vision#citation. E.g., 

```
doi = {https://doi.org/10.1016/j.solener.2022.06.031},
url = {https://www.sciencedirect.com/science/article/pii/S0038092X22004571},
```

**Comment by X-Chen97** [comment]
Thanks for the comment. I added the citation to PV-VISION
