### ISSUE TITLE
problem tuning parameters for vertical and horizontal edges in transform_contourn tutorial

### ISSUE THREAD

**Issue by Eneko82** [hackingmaterials/pv-vision#8]
Hello,
I’m trying to learn from tutorials, but I have an issue when working with the transform_contourn.ipnb. I open the file in Jupiter notebook, but I found this issue when tuning the parameters for vertical edges; The predefined parameters for the example doesn’t works, I tried to tune the parameters with no positive results. Could you provide appropriate parameters for the example? These parameters need to be tunned for each images or can it be automated? 
 
I would like to run the code in a py file but I have the dought if the code need the interactive tuning of the parameters for each image or it can be adjust for one image a run for “similar images= images from the same module at similar conditions.”
![Captura de pantalla 2023-02-15 080043](https://user-images.githubusercontent.com/125037143/218957230-823bc277-c289-49ea-8c94-aa7a54cd04d0.jpg)

**Comment by Eneko82** [comment]
The error message focus on ipywidgets\widgets\interaction.py. I have the ipywidgets 7.6.3 library but I can’t found the interaction.py inside. I checked older version of ipywidgets but I can’t find the interaction.py. What version should I use to run the notebook?

**Comment by X-Chen97** [comment]
Hello! How did you install PV-Vision? If you install it from PyPI, can you check the latest version which is 0.2.4? If you install it from the source, I cannot generate this issue on my side.
