### ISSUE TITLE
non interactive code

### ISSUE THREAD

**Issue by Eneko82** [hackingmaterials/pv-vision#9]
•	We would like to run this code in python file (.py). To that end we have commented (#) interactive function and define the functions parameters manually. For example:
![image](https://user-images.githubusercontent.com/125037143/220116295-49fb2c78-dec1-4ba4-8877-980060837d50.png)

 
Please find attached the modified notebook which no interative imput of parameters(NoNinteractive.ipynb).
This works well for the mask generation (update_mask), corners detection (update corners) and update edges function. However, when we reached to cells cropping, we get this error:

![image](https://user-images.githubusercontent.com/125037143/220116417-db58f322-ef55-4109-8ccc-383d7c81c630.png)

 

After debugging it seems that interactive function is really needed for update edges function. We don’t want to modify your update edges function. So, the question is, is it possible to call this function without using interactive in .py file? Or interactive is needed ? or there is another problem which cells cropping?

**Comment by X-Chen97** [comment]
Could you please provide more details when you run this code in jupyter notebook? That is to say, can you process this module image in an interactive mode? 

I want to check if this issue is triggered by interactive code or failure of detecting internal peaks.

**Comment by X-Chen97** [comment]
I am going to close this issue. If you meet new problems, feel free to ask!
